# Numpy matrix

In [2]:
import numpy as np
from random import randint

In [3]:
grades = np.array([randint(0,10) for i in range(12)])

In [4]:
grades

array([ 9,  6, 10,  0,  4,  7,  6,  6,  0,  9,  1,  9])

get the mean value of the array

In [5]:
print(f'The average grade of the class is {grades.mean():.2f}.')

The average grade of the class is 5.58.


### Vectorisation: apply one operation to all elements of the matrix
### Broadcasting: extend the dimensions of the matrix to perform certain operations
In this case, the scalar `1.5` is extended to a matrix of the same dimensions of `grades` to perform a matrix addition. This illustrates the principle of **broadcasting**

In [6]:
print(grades)
# add 1.5 points to every mark
print( grades + 1.5)

[ 9  6 10  0  4  7  6  6  0  9  1  9]
[10.5  7.5 11.5  1.5  5.5  8.5  7.5  7.5  1.5 10.5  2.5 10.5]


Get only the grades of students who have passed the exam.

In [7]:

pass_grades = np.array([mark for mark in grades if mark >=5])
print(f'Only {len(pass_grades)} students have passed the exam. That\'s the {len(pass_grades)/len(grades):.2%}.')
print(f'Their marks are:\n{pass_grades}')

Only 8 students have passed the exam. That's the 66.67%.
Their marks are:
[ 9  6 10  7  6  6  9  9]


## Multidimensional arrays
`array.reshape(dimensions)` creates a multidimensional array with the specified dimensions.  
Next code creates a multidimensional matrix of 2 "pages" with each one containing a 2x3 matrix  
np.array.shape (_is a matrix attribute_) returns the dimensions of the matrix

In [8]:
# Create a matrix of 2 "pages" with each one containing a 2x3 matrix
temperatures = np.array([29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
                        12.6, 49.9, 38.6, 31.3, 9.2, 22.2]).reshape(2, 2, 3)
temperatures.shape

(2, 2, 3)

## Getting the transpose of an array: `np.ndarray.swapaxes(array, axis_1, axis_2)`
### Axis of array are zero-indexed. Swapping axis_1 and axis_2 is equivalent to swapping rows and columns

In [9]:
print('Original array:')
print(temperatures)
print('\nTranspose of array:')
np.swapaxes(temperatures, 1, 2)

Original array:
[[[29.3 42.1 18.8]
  [16.1 38.  12.5]]

 [[12.6 49.9 38.6]
  [31.3  9.2 22.2]]]

Transpose of array:


array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

### Array methods can change their results depending on which axis they are acting on

In [10]:
table = np.array([
                [5, 3, 7, 1],
                [2, 6, 7 ,9],
                [1, 1, 1, 1],
                [4, 3, 2, 0],
                ])
print(f'The maximum value of the table is {table.max()}')
print(f'The maximum value of each row is: {table.max(axis=0)}')
print(f'The maximum value of each column is: {table.max(axis=1)}')

The maximum value of the table is 9
The maximum value of each row is: [5 6 7 9]
The maximum value of each column is: [7 9 1 4]


## Create an array of consecutive elements using `numpy.arange(size)`
### Broadcasting can be done only if one of the matrix axes has size of 1 or if axes in both arrays are the same size

In [11]:
array_2by2 = np.arange(4).reshape(1,2,2)
array_1by2 = np.arange(2).reshape(1,1,2)
array_2by2 + array_1by2

array([[[0, 2],
        [2, 4]]])

## Array slicing  
Rows and columns slices must be separated by commas. Within a row or a column, normal slicing with colon is used

In [12]:
square = np.array([
                    [16, 3, 2, 13],
                    [5, 10, 11, 8],
                    [9, 6, 7, 12],
                    [4, 15, 14, 1]
                    ])

In [13]:
print(f'2nd row of array is: {square[1,:]}')
print(f'2nd column of array is {square[:,1]}')
print('Elements of last column in the 2nd and 3rd rows:')
print(square[1:3,-1])

2nd row of array is: [ 5 10 11  8]
2nd column of array is [ 3 10  6 15]
Elements of last column in the 2nd and 3rd rows:
[ 8 12]


## linear spaced elements in an array  
Create an array using `numpy.linspace(start, stop, number_of_elements)`

In [14]:
spaced = np.linspace(10,50,9, dtype=int).reshape(3,-1)
# using -1 as argument for number of columns in reshape
# forces reshape to work out the amount of columns to fit all elements of array
spaced

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

## Apply a mask to the elements of array based on fullfiling certain condition

In [16]:
print('Array of random numbers between 1 and 100.')
print(array := np.array([randint(1,100) for i in range(25)]).reshape(5,-1))
print('\nSelection of even elements of original array:')
mask1= array % 2 == 0  # take only even numbers
print(array_masked1 := array[mask1])
print('\nOnly even elements greater or equal to 30 are showed:')
mask2 = array_masked1 >= 30  # select even numbers greater or equal to 30
print(array_masked2 := array_masked1[mask2])

Array of random numbers between 1 and 100.
[[85  7 13 91  5]
 [12 80 39 48 96]
 [43 79 10 57 24]
 [34 20 44 59 86]
 [93 82 56 98 10]]

Selection of even elements of original array:
[12 80 48 96 10 24 34 20 44 86 82 56 98 10]

Only even elements greater or equal to 30 are showed:
[80 48 96 34 44 86 82 56 98]


## Combining masks to filter array elements

### Filter array elements by applying one mask after another

In [17]:
print('\nOdd elements multiples of 3:')
array_odds = array[array %2 !=0]
array_odds_multiple3 = array_odds[ array_odds % 3 == 0]
print(array_odds_multiple3)


Odd elements multiples of 3:
[39 57 93]


### Now let's combine two masks at the same time  
Use of `&` binary operator to concatenate conditions

In [19]:
print('\nOdd elements multiples of 3:')
print(array_odds_multiple3 := array[(array % 2 !=0) & (array % 3 == 0)])


Odd elements multiples of 3:
[39 57 93]


## Transposing an array

In [23]:
print(a := np.array([randint(-10,10) for i in range(12)]).reshape(3,4))


[[-8  2 -3 -6]
 [ 8 -8  5 -9]
 [ 3  7  3  3]]


### 1st method of transposing an array:  
Using `T` attribute of ndarray

In [24]:
print(a.T)

[[-8  8  3]
 [ 2 -8  7]
 [-3  5  3]
 [-6 -9  3]]


### 2nd method of transposing an array:  
Using `transpose()` method

In [26]:
print(a.transpose())

[[-8  8  3]
 [ 2 -8  7]
 [-3  5  3]
 [-6 -9  3]]


### 3rd method of transposing an array:  
Using `numpy.swapaxes(array, axis 1, axis 2)`

In [29]:
print(np.swapaxes(a, 0,1))

[[-8  8  3]
 [ 2 -8  7]
 [-3  5  3]
 [-6 -9  3]]
