# How to solve a linear system

In [1]:
from IPython.display import display, Math
import numpy as np

Ahora consultamos cuántas ecuaciones y cuántas incógnitas tenemos

In [7]:
equations = int(input('¿Cuántas ecuaciones? '))
unknowns =  int(input('¿Cuántas incógnitas? '))

In [16]:
coeficients = []
independent_terms = []
for i in range(equations):
    coeficients.append([])
    for k in range(unknowns):
        coeficients[i].append(int(input(f'Ecuación {i+1}, coeficiente {k+1}: ')))
    indep_term = int(input(f'Término independiente de la ecuación {i+1}: '))
    independent_terms.append([indep_term])

La matriz de coeficientes es:
 [[ 2  3]
 [-1  4]]
La matriz de términos coeficientes es:
 [[0]
 [2]]


### Creamos las matrices usando numpy

In [46]:
A = np.array(coeficients)
B = np.array(independent_terms)

Imprimimos las matrices:

In [47]:
print(f'La matriz de coeficientes es:\n {A}')
print(f'La matriz de términos coeficientes es:\n {B}')

La matriz de coeficientes es:
 [[ 2  3]
 [-1  4]]
La matriz de términos coeficientes es:
 [[0]
 [2]]


### El sistema a resolver es el siguiente:

In [34]:
display(Math(f'{A[0][0]}x+{A[0][1]}y = {B[0][0]}'))
display(Math(f'{A[1][0]}x+{A[1][1]}y = {B[1][0]}'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Usamos el método `np.linalg.solve(coeficients, indep_terms)` para resolver el sistema.

In [48]:
Ainv = np.linalg.inv(A)
X = np.linalg.solve(A,B)

In [45]:
print('Las soluciones son: ', end='')
display(Math(f'x = {X[0][0]:.2f},  y = {X[1][0]:.2f}'))

Las soluciones son: 

<IPython.core.display.Math object>